data:
  raw: data/raw/winequality-red.csv
  intermediate: data/intermediate
model: model/svm
process:
  feature: quality
  test_size: 0.2
train:
  hyperparameters:
    svm__kernel:
    - linear
    svm__C:
    - 0.1
    - 1
    - 11
    svm__gamma:
    - 0.5
    - 2
    - 10
  grid_search:
    cv: 2
    scoring: accuracy
    verbose: 3